-- =============================================================================
-- Migration: Premier League kits → shirt + supporter's scarf (no shorts or socks)
-- Date: 2026-10-15. Safe to re-run. Run after 2026-10-14-team-outfit-slugs.sql.
--
-- Rewrites the prompt description (clothing_description) of the 20 Premier League team
-- outfits, matched by slug (team-premier-league-<team>). Generated from
-- lib/collections/sports-teams.ts (teamOutfit). This replaces any hand edits to these 20
-- descriptions. Other leagues' kits are unchanged; every team's team-switch (recolour)
-- prompt is refreshed so a scarf is recoloured too.
-- =============================================================================

BEGIN;

UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Arsenal colours (red and white): red shirt with white sleeves and white collar. Worn with a knitted supporter''s scarf in red and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-arsenal';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Villa colours (claret, sky blue and white): claret shirt with sky-blue sleeves. Worn with a knitted supporter''s scarf in claret, sky blue and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-aston-villa';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Bournemouth colours (red and black): red and black vertical-striped shirt. Worn with a knitted supporter''s scarf in red and black bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-bournemouth';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Brentford colours (red, white and black): red and white vertical-striped shirt. Worn with a knitted supporter''s scarf in red, white and black bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-brentford';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Brighton colours (blue and white): blue and white vertical-striped shirt. Worn with a knitted supporter''s scarf in blue and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-brighton';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Chelsea colours (royal blue and white): royal-blue shirt with white trim. Worn with a knitted supporter''s scarf in royal blue and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-chelsea';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Coventry colours (sky blue and white): sky-blue shirt with white trim. Worn with a knitted supporter''s scarf in sky blue and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-coventry-city';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Palace colours (red and blue): red and blue vertical-striped shirt. Worn with a knitted supporter''s scarf in red and blue bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-crystal-palace';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Everton colours (royal blue and white): royal-blue shirt with white trim. Worn with a knitted supporter''s scarf in royal blue and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-everton';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Fulham colours (white and black): white shirt with black trim. Worn with a knitted supporter''s scarf in white and black bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-fulham';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Hull colours (amber and black): amber shirt with black trim and thin black stripes. Worn with a knitted supporter''s scarf in amber and black bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-hull-city';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Ipswich colours (blue and white): blue shirt with white collar and trim. Worn with a knitted supporter''s scarf in blue and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-ipswich-town';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Leeds colours (white, blue and yellow): all-white shirt with blue and yellow trim. Worn with a knitted supporter''s scarf in white, blue and yellow bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-leeds-united';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Liverpool colours (red and white): red shirt with white trim. Worn with a knitted supporter''s scarf in red and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-liverpool';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Man City colours (sky blue, white and navy): sky-blue shirt with navy trim. Worn with a knitted supporter''s scarf in sky blue, white and navy bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-manchester-city';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Man United colours (red, white and black): red shirt with white and black trim. Worn with a knitted supporter''s scarf in red, white and black bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-manchester-united';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Newcastle colours (black and white): black and white vertical-striped shirt. Worn with a knitted supporter''s scarf in black and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-newcastle-united';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Forest colours (Garibaldi red and white): bright red shirt. Worn with a knitted supporter''s scarf in Garibaldi red and white bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-nottingham-forest';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Sunderland colours (red, white and black): red and white vertical-striped shirt. Worn with a knitted supporter''s scarf in red, white and black bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-sunderland';
UPDATE public.outfits SET clothing_description = 'a football (soccer) shirt: short-sleeved jersey-style top, in Spurs colours (white and navy): white shirt with navy trim. Worn with a knitted supporter''s scarf in white and navy bar stripes around the neck. Only the shirt and scarf: no shorts, socks or boots. Plain fabric with no logos, crests, badges, lettering or sponsor marks.', updated_at = now()
 WHERE slug = 'team-premier-league-tottenham-hotspur';

-- Team-switch prompt for every team now also recolours a scarf, if the design has one
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Arsenal colours (red and white): red top with white sleeves and white collar. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red shirt with white sleeves and white collar'::text), updated_at = now()
 WHERE path = 'sports/premier-league/arsenal';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Villa colours (claret, sky blue and white): claret top with sky-blue sleeves. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'claret shirt with sky-blue sleeves'::text), updated_at = now()
 WHERE path = 'sports/premier-league/aston-villa';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bournemouth colours (red and black): red and black vertical-striped top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red and black vertical-striped shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/bournemouth';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Brentford colours (red, white and black): red and white vertical-striped top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red and white vertical-striped shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/brentford';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Brighton colours (blue and white): blue and white vertical-striped top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue and white vertical-striped shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/brighton';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Chelsea colours (royal blue and white): royal-blue top with white trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue shirt with white trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/chelsea';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Coventry colours (sky blue and white): sky-blue top with white trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'sky-blue shirt with white trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/coventry-city';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Palace colours (red and blue): red and blue vertical-striped top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red and blue vertical-striped shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/crystal-palace';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Everton colours (royal blue and white): royal-blue top with white trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue shirt with white trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/everton';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Fulham colours (white and black): white top with black trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'white shirt with black trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/fulham';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Hull colours (amber and black): amber top with black trim and thin black stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'amber shirt with black trim and thin black stripes'::text), updated_at = now()
 WHERE path = 'sports/premier-league/hull-city';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Ipswich colours (blue and white): blue top with white collar and trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue shirt with white collar and trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/ipswich-town';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Leeds colours (white, blue and yellow): all-white top with blue and yellow trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'all-white shirt with blue and yellow trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/leeds-united';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Liverpool colours (red and white): red top with white trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red shirt with white trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/liverpool';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Man City colours (sky blue, white and navy): sky-blue top with navy trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'sky-blue shirt with navy trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/manchester-city';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Man United colours (red, white and black): red top with white and black trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red shirt with white and black trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/manchester-united';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Newcastle colours (black and white): black and white vertical-striped top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black and white vertical-striped shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/newcastle-united';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Forest colours (Garibaldi red and white): bright red top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'bright red shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/nottingham-forest';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Sunderland colours (red, white and black): red and white vertical-striped top. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red and white vertical-striped shirt'::text), updated_at = now()
 WHERE path = 'sports/premier-league/sunderland';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Spurs colours (white and navy): white top with navy trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'white shirt with navy trim'::text), updated_at = now()
 WHERE path = 'sports/premier-league/tottenham-hotspur';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bills colours (royal blue, red and white): royal-blue top with white numbers and red-white-blue sleeve stripes, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue jersey with white numbers and red-white-blue sleeve stripes, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/buffalo-bills';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Dolphins colours (aqua, orange and white): aqua top with white numbers outlined in orange, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'aqua jersey with white numbers outlined in orange, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/miami-dolphins';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Patriots colours (navy, red and silver): navy top with white numbers and red trim, silver bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy jersey with white numbers and red trim, silver pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/new-england-patriots';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Jets colours (green and white): green top with white numbers and white shoulder stripes, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'green jersey with white numbers and white shoulder stripes, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/new-york-jets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Ravens colours (purple, black and gold): purple top with white numbers trimmed in black and gold, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple jersey with white numbers trimmed in black and gold, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/baltimore-ravens';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bengals colours (orange and black): black top with orange tiger-stripe shoulders and orange numbers, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black jersey with orange tiger-stripe shoulders and orange numbers, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/cincinnati-bengals';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Browns colours (brown, orange and white): brown top with orange and white sleeve stripes and white numbers, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'brown jersey with orange and white sleeve stripes and white numbers, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/cleveland-browns';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Steelers colours (black and gold): black top with gold numbers and gold sleeve stripes, gold bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black jersey with gold numbers and gold sleeve stripes, gold pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/pittsburgh-steelers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Texans colours (deep steel blue, battle red and white): deep navy top with white numbers outlined in red, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'deep navy jersey with white numbers outlined in red, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/houston-texans';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Colts colours (royal blue and white): royal-blue top with white numbers and white shoulder stripes, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue jersey with white numbers and white shoulder stripes, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/indianapolis-colts';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Jaguars colours (teal, black and gold): teal top with white numbers trimmed in gold and black, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'teal jersey with white numbers trimmed in gold and black, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/jacksonville-jaguars';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Titans colours (navy, Titans blue and red): navy top with light-blue shoulders and white numbers, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy jersey with light-blue shoulders and white numbers, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/tennessee-titans';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Broncos colours (orange, navy and white): orange top with navy numbers trimmed in white, white bottoms with orange stripe. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'orange jersey with navy numbers trimmed in white, white pants with orange stripe'::text), updated_at = now()
 WHERE path = 'sports/nfl/denver-broncos';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Chiefs colours (red, gold and white): red top with white numbers and gold-trimmed sleeve stripes, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red jersey with white numbers and gold-trimmed sleeve stripes, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/kansas-city-chiefs';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Raiders colours (black and silver): black top with silver-outlined white numbers, silver bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black jersey with silver-outlined white numbers, silver pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/las-vegas-raiders';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Chargers colours (powder blue, sunshine gold and white): powder-blue top with white numbers and gold lightning-bolt shoulder stripes, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'powder-blue jersey with white numbers and gold lightning-bolt shoulder stripes, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/los-angeles-chargers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Cowboys colours (navy, silver and white): white top with navy numbers and navy-and-grey sleeve stripes, metallic silver-blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'white jersey with navy numbers and navy-and-grey sleeve stripes, metallic silver-blue pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/dallas-cowboys';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Giants colours (blue, red and white): dark-blue top with white numbers trimmed in red, grey bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'dark-blue jersey with white numbers trimmed in red, grey pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/new-york-giants';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Eagles colours (midnight green, silver and white): midnight-green top with white numbers and silver trim, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'midnight-green jersey with white numbers and silver trim, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/philadelphia-eagles';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Commanders colours (burgundy, gold and white): burgundy top with gold numbers, gold bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'burgundy jersey with gold numbers, gold pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/washington-commanders';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bears colours (navy, orange and white): navy top with white numbers and orange-white sleeve stripes, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy jersey with white numbers and orange-white sleeve stripes, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/chicago-bears';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Lions colours (Honolulu blue, silver and white): Honolulu-blue top with white numbers, silver bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'Honolulu-blue jersey with white numbers, silver pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/detroit-lions';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Packers colours (green, gold and white): dark-green top with white numbers and gold-white sleeve stripes, gold bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'dark-green jersey with white numbers and gold-white sleeve stripes, gold pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/green-bay-packers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Vikings colours (purple, gold and white): purple top with white numbers trimmed in gold, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple jersey with white numbers trimmed in gold, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/minnesota-vikings';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Falcons colours (red, black and white): black top with red trim and white numbers, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black jersey with red trim and white numbers, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/atlanta-falcons';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Panthers colours (black, Panther blue and silver): black top with blue-outlined white numbers, silver bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black jersey with blue-outlined white numbers, silver pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/carolina-panthers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Saints colours (black, old gold and white): black top with old-gold-outlined white numbers, old-gold bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black jersey with old-gold-outlined white numbers, old-gold pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/new-orleans-saints';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Buccaneers colours (red, pewter and orange): red top with pewter numbers trimmed in orange, pewter bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red jersey with pewter numbers trimmed in orange, pewter pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/tampa-bay-buccaneers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Cardinals colours (cardinal red, black and white): cardinal-red top with white numbers and black trim, white bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'cardinal-red jersey with white numbers and black trim, white pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/arizona-cardinals';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Rams colours (royal blue, sol yellow and white): royal-blue top with yellow numbers and yellow horn-curl shoulder stripes, yellow bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue jersey with yellow numbers and yellow horn-curl shoulder stripes, yellow pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/los-angeles-rams';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to 49ers colours (scarlet, gold and white): scarlet top with white numbers outlined in black, gold bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'scarlet jersey with white numbers outlined in black, gold pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/san-francisco-49ers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Seahawks colours (college navy, action green and wolf grey): navy top with white numbers outlined in action green, navy bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy jersey with white numbers outlined in action green, navy pants'::text), updated_at = now()
 WHERE path = 'sports/nfl/seattle-seahawks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Hawks colours (torch red, volt green and white): red top with white numbers and volt-green trim, red bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red vest with white numbers and volt-green trim, red shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/atlanta-hawks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Celtics colours (green, white and gold): green top with white numbers trimmed in gold, green bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'green vest with white numbers trimmed in gold, green shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/boston-celtics';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Nets colours (black and white): black top with white numbers and white trim, black bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black vest with white numbers and white trim, black shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/brooklyn-nets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Hornets colours (teal, purple and white): teal top with purple-outlined white numbers and pinstripes, teal bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'teal vest with purple-outlined white numbers and pinstripes, teal shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/charlotte-hornets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bulls colours (red, black and white): red top with white numbers outlined in black, red bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red vest with white numbers outlined in black, red shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/chicago-bulls';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Cavaliers colours (wine, gold and navy): wine-red top with gold numbers and navy trim, wine bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'wine-red vest with gold numbers and navy trim, wine shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/cleveland-cavaliers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Pistons colours (red, royal blue and white): royal-blue top with red numbers outlined in white, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue vest with red numbers outlined in white, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/detroit-pistons';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Pacers colours (navy, gold and white): navy top with gold numbers, navy bottoms with gold stripe. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy vest with gold numbers, navy shorts with gold stripe'::text), updated_at = now()
 WHERE path = 'sports/nba/indiana-pacers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Heat colours (red, black and yellow): black top with red numbers and red-yellow trim, black bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black vest with red numbers and red-yellow trim, black shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/miami-heat';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bucks colours (Good Land green, Cream City cream and blue): dark-green top with cream numbers, green bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'dark-green vest with cream numbers, green shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/milwaukee-bucks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Knicks colours (blue, orange and white): blue top with orange numbers outlined in white, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue vest with orange numbers outlined in white, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/new-york-knicks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Magic colours (blue, black and silver): black top with blue numbers and blue pinstripes, black bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black vest with blue numbers and blue pinstripes, black shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/orlando-magic';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to 76ers colours (blue, red and white): blue top with white numbers trimmed in red, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue vest with white numbers trimmed in red, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/philadelphia-76ers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Raptors colours (red, black and silver): red top with white numbers trimmed in black, red bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red vest with white numbers trimmed in black, red shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/toronto-raptors';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Wizards colours (navy, red and white): navy top with white numbers and red trim, navy bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy vest with white numbers and red trim, navy shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/washington-wizards';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Mavericks colours (royal blue, navy and silver): royal-blue top with white numbers trimmed in silver, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue vest with white numbers trimmed in silver, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/dallas-mavericks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Nuggets colours (midnight blue, sunshine yellow and flatirons red): midnight-blue top with sunshine-yellow numbers and red trim, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'midnight-blue vest with sunshine-yellow numbers and red trim, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/denver-nuggets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Warriors colours (royal blue, gold and white): royal-blue top with gold numbers and gold trim, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue vest with gold numbers and gold trim, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/golden-state-warriors';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Rockets colours (red, black and silver): red top with white numbers trimmed in black, red bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red vest with white numbers trimmed in black, red shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/houston-rockets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Clippers colours (blue, red and black): blue top with white numbers trimmed in red, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue vest with white numbers trimmed in red, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/los-angeles-clippers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Lakers colours (purple, gold and white): gold top with purple numbers outlined in white, gold bottoms with purple stripe. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'gold vest with purple numbers outlined in white, gold shorts with purple stripe'::text), updated_at = now()
 WHERE path = 'sports/nba/los-angeles-lakers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Grizzlies colours (Beale Street blue, navy and gold): navy top with Beale Street blue numbers and gold trim, navy bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy vest with Beale Street blue numbers and gold trim, navy shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/memphis-grizzlies';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Timberwolves colours (midnight blue, lake blue and aurora green): midnight-blue top with white numbers and green trim, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'midnight-blue vest with white numbers and green trim, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/minnesota-timberwolves';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Pelicans colours (navy, red and gold): navy top with white numbers trimmed in red and gold, navy bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy vest with white numbers trimmed in red and gold, navy shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/new-orleans-pelicans';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Thunder colours (blue, sunset orange and navy): blue top with white numbers and orange trim, blue bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue vest with white numbers and orange trim, blue shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/oklahoma-city-thunder';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Suns colours (purple, orange and yellow): purple top with orange numbers outlined in white, purple bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple vest with orange numbers outlined in white, purple shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/phoenix-suns';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Trail Blazers colours (red, black and white): black top with white numbers and a red diagonal stripe, black bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black vest with white numbers and a red diagonal stripe, black shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/portland-trail-blazers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Kings colours (purple, silver and black): purple top with white numbers trimmed in silver, purple bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple vest with white numbers trimmed in silver, purple shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/sacramento-kings';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Spurs colours (black, silver and white): black top with silver-outlined white numbers, black bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black vest with silver-outlined white numbers, black shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/san-antonio-spurs';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Jazz colours (purple, black and white): purple top with white numbers and black trim, purple bottoms. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple vest with white numbers and black trim, purple shorts'::text), updated_at = now()
 WHERE path = 'sports/nba/utah-jazz';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Bruins colours (black, gold and white): black top with gold and white hem and sleeve stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black sweater with gold and white hem and sleeve stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/boston-bruins';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Sabres colours (royal blue, gold and white): royal-blue top with gold and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue sweater with gold and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/buffalo-sabres';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Red Wings colours (red and white): red top with a white hem stripe and white sleeve band. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with a white hem stripe and white sleeve band'::text), updated_at = now()
 WHERE path = 'sports/nhl/detroit-red-wings';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Panthers colours (red, navy and gold): red top with navy and gold stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with navy and gold stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/florida-panthers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Canadiens colours (red, blue and white): red top with a broad blue-and-white chest band and sleeve stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with a broad blue-and-white chest band and sleeve stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/montreal-canadiens';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Senators colours (red, black and gold): red top with black and gold stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with black and gold stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/ottawa-senators';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Lightning colours (blue and white): blue top with white hem and sleeve stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue sweater with white hem and sleeve stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/tampa-bay-lightning';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Maple Leafs colours (blue and white): blue top with white hem and sleeve stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue sweater with white hem and sleeve stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/toronto-maple-leafs';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Hurricanes colours (red, black and white): red top with black and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with black and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/carolina-hurricanes';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Blue Jackets colours (union blue, goal red and white): navy top with red and white trim. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy sweater with red and white trim'::text), updated_at = now()
 WHERE path = 'sports/nhl/columbus-blue-jackets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Devils colours (red, black and white): red top with black and white hem and sleeve stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with black and white hem and sleeve stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/new-jersey-devils';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Islanders colours (royal blue, orange and white): royal-blue top with orange and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue sweater with orange and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/new-york-islanders';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Rangers colours (blue, red and white): blue top with red and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue sweater with red and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/new-york-rangers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Flyers colours (orange, black and white): orange top with black and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'orange sweater with black and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/philadelphia-flyers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Penguins colours (black, gold and white): black top with gold and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black sweater with gold and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/pittsburgh-penguins';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Capitals colours (red, navy and white): red top with navy and white stripes and white stars on the hem. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with navy and white stripes and white stars on the hem'::text), updated_at = now()
 WHERE path = 'sports/nhl/washington-capitals';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Mammoth colours (rock black, mountain blue and salt white): black top with mountain-blue and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black sweater with mountain-blue and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/utah-mammoth';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Blackhawks colours (red, black and white): red top with black and white hem stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with black and white hem stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/chicago-blackhawks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Avalanche colours (burgundy, steel blue and white): burgundy top with steel-blue and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'burgundy sweater with steel-blue and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/colorado-avalanche';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Stars colours (victory green, silver and black): victory-green top with silver and black stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'victory-green sweater with silver and black stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/dallas-stars';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Wild colours (forest green, iron range red and wheat): forest-green top with red and wheat stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'forest-green sweater with red and wheat stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/minnesota-wild';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Predators colours (gold, navy and white): gold top with navy and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'gold sweater with navy and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/nashville-predators';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Blues colours (blue, gold and navy): blue top with gold and navy stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue sweater with gold and navy stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/st-louis-blues';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Jets colours (navy, blue and silver): navy top with blue and silver stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy sweater with blue and silver stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/winnipeg-jets';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Ducks colours (orange, black and gold): black top with orange and gold stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black sweater with orange and gold stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/anaheim-ducks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Flames colours (red, gold and black): red top with gold and black stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red sweater with gold and black stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/calgary-flames';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Oilers colours (royal blue, orange and white): royal-blue top with orange and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue sweater with orange and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/edmonton-oilers';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Kings colours (black, silver and white): black top with silver and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black sweater with silver and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/los-angeles-kings';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Sharks colours (Pacific teal, black and orange): teal top with black and orange stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'teal sweater with black and orange stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/san-jose-sharks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Kraken colours (deep sea blue, ice blue and red): deep-sea-blue top with ice-blue and red stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'deep-sea-blue sweater with ice-blue and red stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/seattle-kraken';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Golden Knights colours (steel grey, gold and red): steel-grey top with gold and black stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'steel-grey sweater with gold and black stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/vegas-golden-knights';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Canucks colours (blue, green and white): blue top with green and white stripes. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'blue sweater with green and white stripes'::text), updated_at = now()
 WHERE path = 'sports/nhl/vancouver-canucks';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Texas colours (burnt orange and white): burnt-orange top with white sleeves and burnt-orange-and-white striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'burnt-orange varsity jacket with white sleeves and burnt-orange-and-white striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/texas';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Alabama colours (crimson and white): crimson top with white sleeves and crimson-and-white striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'crimson varsity jacket with white sleeves and crimson-and-white striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/alabama';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Georgia colours (red and black): red top with black sleeves and red-and-black striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red varsity jacket with black sleeves and red-and-black striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/georgia';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Michigan colours (blue and maize): navy-blue top with maize-yellow sleeves and blue-and-maize striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy-blue varsity jacket with maize-yellow sleeves and blue-and-maize striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/michigan';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Ohio State colours (scarlet, grey and white): scarlet top with grey sleeves and scarlet-and-grey striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'scarlet varsity jacket with grey sleeves and scarlet-and-grey striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/ohio-state';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Notre Dame colours (navy, gold and green): navy top with gold sleeves and navy-and-gold striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy varsity jacket with gold sleeves and navy-and-gold striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/notre-dame';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to LSU colours (purple and gold): purple top with gold sleeves and purple-and-gold striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple varsity jacket with gold sleeves and purple-and-gold striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/lsu';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Texas A&M colours (maroon and white): maroon top with white sleeves and maroon-and-white striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'maroon varsity jacket with white sleeves and maroon-and-white striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/texas-am';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Oklahoma colours (crimson and cream): crimson top with cream sleeves and crimson-and-cream striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'crimson varsity jacket with cream sleeves and crimson-and-cream striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/oklahoma';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Florida colours (orange and blue): royal-blue top with orange sleeves and blue-and-orange striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'royal-blue varsity jacket with orange sleeves and blue-and-orange striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/florida';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Tennessee colours (orange, white and smokey grey): bright-orange top with white sleeves and orange-and-white striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'bright-orange varsity jacket with white sleeves and orange-and-white striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/tennessee';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Auburn colours (navy and orange): navy top with orange sleeves and navy-and-orange striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy varsity jacket with orange sleeves and navy-and-orange striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/auburn';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Clemson colours (orange and regalia purple): orange top with purple sleeves and orange-and-purple striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'orange varsity jacket with purple sleeves and orange-and-purple striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/clemson';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to USC colours (cardinal and gold): cardinal-red top with gold sleeves and cardinal-and-gold striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'cardinal-red varsity jacket with gold sleeves and cardinal-and-gold striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/usc';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Penn State colours (navy and white): navy top with white sleeves and navy-and-white striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'navy varsity jacket with white sleeves and navy-and-white striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/penn-state';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Florida State colours (garnet and gold): garnet top with gold sleeves and garnet-and-gold striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'garnet varsity jacket with gold sleeves and garnet-and-gold striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/florida-state';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Oregon colours (green and yellow): green top with yellow sleeves and green-and-yellow striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'green varsity jacket with yellow sleeves and green-and-yellow striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/oregon';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Washington colours (purple and gold): purple top with gold sleeves and purple-and-gold striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'purple varsity jacket with gold sleeves and purple-and-gold striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/washington';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Cincinnati colours (red and black): red top with black sleeves and red-and-black striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'red varsity jacket with black sleeves and red-and-black striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/cincinnati';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Missouri colours (gold and black): black top with old-gold sleeves and black-and-gold striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'black varsity jacket with old-gold sleeves and black-and-gold striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/missouri';
UPDATE public.collections SET metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('recolour_prompt', 'Recolour the pet''s sports outfit (and its scarf, if it has one) to Miami colours (orange, green and white): green top with orange sleeves and green-orange-white striped cuffs. Keep the same type of garment, cut, folds, pose, background and lighting; change only the colours and stripes. Plain fabric with no logos, crests, badges, lettering or sponsor marks.'::text, 'kit', 'green varsity jacket with orange sleeves and green-orange-white striped cuffs'::text), updated_at = now()
 WHERE path = 'sports/college/miami';

COMMIT;

-- Check: should list 20 rows, none mentioning shorts or socks except in "no shorts, socks or boots"
SELECT name, clothing_description FROM public.outfits WHERE slug LIKE 'team-premier-league-%' ORDER BY name;
