-- Migration: Add Multi-Subject Support and AI Composition Analysis
-- Date: 2026-02-15
-- Purpose: Transform image_catalog to support multiple subjects per image with AI-powered composition analysis
-- CRITICAL: This migration is backward compatible and can be rolled back

-- =============================================================================
-- 1. ADD NEW COLUMNS TO IMAGE_CATALOG
-- =============================================================================

-- Multi-subject support
ALTER TABLE public.image_catalog
  ADD COLUMN IF NOT EXISTS is_multi_subject boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS subjects jsonb DEFAULT '[]'::jsonb;

-- AI composition analysis
ALTER TABLE public.image_catalog
  ADD COLUMN IF NOT EXISTS composition_analysis text,
  ADD COLUMN IF NOT EXISTS composition_metadata jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS ai_analysis_model text DEFAULT 'claude-sonnet-4-5',
  ADD COLUMN IF NOT EXISTS ai_analyzed_at timestamp with time zone;

-- Marketing and variation generation
ALTER TABLE public.image_catalog
  ADD COLUMN IF NOT EXISTS marketing_description text,
  ADD COLUMN IF NOT EXISTS marketing_description_approved boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS variation_prompt_template text;

-- Add comments
COMMENT ON COLUMN public.image_catalog.is_multi_subject IS
  'TRUE if image contains multiple subjects (e.g., two dogs, dog and cat). FALSE for single subject images.';

COMMENT ON COLUMN public.image_catalog.subjects IS
  'JSONB array of subjects in the image. Structure: [{"subject_order": 1, "is_primary": true, "breed_id": "uuid", "coat_id": "uuid", "position": "left", "size_prominence": "equal", "pose_description": "sitting", "identified_by_ai": true, "ai_confidence": 0.95}]';

COMMENT ON COLUMN public.image_catalog.composition_analysis IS
  'Human-readable markdown analysis of image composition (lighting, background, framing, artistic style, subject pose). Generated by Claude AI for admin review and variation prompt construction.';

COMMENT ON COLUMN public.image_catalog.composition_metadata IS
  'Structured JSONB metadata for composition. Structure: {"lighting": {"type": "natural", "direction": "front", "quality": "soft"}, "background": {"type": "solid", "colors": ["#hex"]}, "composition": {"framing": "portrait", "subject_placement": "center"}, "artistic_style": {"medium": "photograph", "texture": "smooth"}, "subject_details": {"pose": "sitting", "gaze": "camera", "expression": "happy"}}';

COMMENT ON COLUMN public.image_catalog.ai_analysis_model IS
  'AI model used for composition analysis (e.g., "claude-sonnet-4-5"). Allows tracking which model version generated the analysis.';

COMMENT ON COLUMN public.image_catalog.ai_analyzed_at IS
  'Timestamp when AI composition analysis was performed. NULL if not yet analyzed or manually uploaded without analysis.';

COMMENT ON COLUMN public.image_catalog.marketing_description IS
  'Marketing-focused description for website display. Generated by Claude AI, editable by admin. Fun, witty tone appealing to pet owners.';

COMMENT ON COLUMN public.image_catalog.marketing_description_approved IS
  'Admin approval flag for marketing description. TRUE after admin review/edit. FALSE for AI-generated drafts awaiting review.';

COMMENT ON COLUMN public.image_catalog.variation_prompt_template IS
  'Precise template for Gemini variation generation. Specifies exactly what must be preserved (background, lighting, composition) and what changes (subject breed/coat). Generated by Claude AI from composition analysis.';

-- =============================================================================
-- 2. CREATE IMAGE_CATALOG_SUBJECTS JUNCTION TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.image_catalog_subjects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  image_id uuid NOT NULL REFERENCES public.image_catalog(id) ON DELETE CASCADE,
  subject_order integer NOT NULL CHECK (subject_order > 0),
  is_primary boolean DEFAULT false,

  -- Subject identification
  breed_id uuid REFERENCES public.breeds(id),
  coat_id uuid REFERENCES public.coats(id),
  outfit_id uuid REFERENCES public.outfits(id),

  -- Spatial positioning
  position_in_frame text CHECK (position_in_frame = ANY (ARRAY['left', 'center', 'right', 'foreground', 'background', 'top-left', 'top-right', 'bottom-left', 'bottom-right'])),
  size_prominence text CHECK (size_prominence = ANY (ARRAY['primary', 'secondary', 'equal', 'dominant', 'minor'])),

  -- AI identification metadata
  identified_by_ai boolean DEFAULT false,
  ai_confidence numeric(3,2) CHECK (ai_confidence >= 0 AND ai_confidence <= 1.00),

  -- Descriptive details
  pose_description text,
  gaze_direction text CHECK (gaze_direction = ANY (ARRAY['camera', 'left', 'right', 'up', 'down', 'away'])),
  expression text,

  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  CONSTRAINT image_catalog_subjects_pkey PRIMARY KEY (id),
  CONSTRAINT image_catalog_subjects_unique_order UNIQUE(image_id, subject_order)
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_catalog_subjects_image_id
  ON public.image_catalog_subjects(image_id);

CREATE INDEX IF NOT EXISTS idx_catalog_subjects_breed_id
  ON public.image_catalog_subjects(breed_id)
  WHERE breed_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_catalog_subjects_coat_id
  ON public.image_catalog_subjects(coat_id)
  WHERE coat_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_catalog_subjects_outfit_id
  ON public.image_catalog_subjects(outfit_id)
  WHERE outfit_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_catalog_subjects_is_primary
  ON public.image_catalog_subjects(is_primary)
  WHERE is_primary = true;

CREATE INDEX IF NOT EXISTS idx_catalog_subjects_position
  ON public.image_catalog_subjects(position_in_frame)
  WHERE position_in_frame IS NOT NULL;

-- Comments
COMMENT ON TABLE public.image_catalog_subjects IS
  'Junction table linking catalog images to multiple subjects (breeds/coats/outfits). Enables efficient filtering by breed/coat while supporting multi-subject images. Each row represents one subject in an image.';

COMMENT ON COLUMN public.image_catalog_subjects.subject_order IS
  'Order/index of subject in image (1, 2, 3...). Used to maintain consistent subject positioning and reference in JSONB subjects array.';

COMMENT ON COLUMN public.image_catalog_subjects.is_primary IS
  'TRUE for the main/dominant subject in image. Only one subject per image should be primary. Used for filtering and display priority.';

COMMENT ON COLUMN public.image_catalog_subjects.position_in_frame IS
  'Spatial position of subject within image frame. Values: left, center, right, foreground, background, top-left, top-right, bottom-left, bottom-right.';

COMMENT ON COLUMN public.image_catalog_subjects.size_prominence IS
  'Relative size/importance of subject in composition. Values: primary (largest/main), secondary (smaller), equal (same size as others), dominant (much larger), minor (much smaller).';

COMMENT ON COLUMN public.image_catalog_subjects.identified_by_ai IS
  'TRUE if breed/coat was identified by Claude AI. FALSE if manually entered by admin. Used to track AI accuracy.';

COMMENT ON COLUMN public.image_catalog_subjects.ai_confidence IS
  'AI confidence score for breed/coat identification (0.00 to 1.00). Higher = more confident. Only set when identified_by_ai = TRUE.';

-- =============================================================================
-- 3. ADD INDEXES TO NEW IMAGE_CATALOG COLUMNS
-- =============================================================================

-- Index for multi-subject filtering
CREATE INDEX IF NOT EXISTS idx_image_catalog_is_multi_subject
  ON public.image_catalog(is_multi_subject)
  WHERE is_multi_subject = true;

-- Index for AI-analyzed images
CREATE INDEX IF NOT EXISTS idx_image_catalog_ai_analyzed
  ON public.image_catalog(ai_analyzed_at DESC)
  WHERE ai_analyzed_at IS NOT NULL;

-- Index for approved marketing descriptions
CREATE INDEX IF NOT EXISTS idx_image_catalog_marketing_approved
  ON public.image_catalog(marketing_description_approved)
  WHERE marketing_description_approved = true;

-- Index for images with composition analysis (for variation generation)
CREATE INDEX IF NOT EXISTS idx_image_catalog_has_composition
  ON public.image_catalog(id)
  WHERE composition_analysis IS NOT NULL;

-- GIN index for subjects JSONB (enables efficient querying)
CREATE INDEX IF NOT EXISTS idx_image_catalog_subjects_gin
  ON public.image_catalog USING gin(subjects);

-- GIN index for composition_metadata JSONB
CREATE INDEX IF NOT EXISTS idx_image_catalog_composition_metadata_gin
  ON public.image_catalog USING gin(composition_metadata);

-- =============================================================================
-- 4. BACKWARD COMPATIBILITY: MIGRATE EXISTING SINGLE-SUBJECT DATA
-- =============================================================================

DO $$
DECLARE
  migrated_count integer := 0;
  total_count integer;
BEGIN
  -- Count total images to migrate
  SELECT COUNT(*) INTO total_count
  FROM public.image_catalog
  WHERE breed_id IS NOT NULL
    AND is_multi_subject = false
    AND subjects = '[]'::jsonb;

  RAISE NOTICE 'Starting backward compatibility migration for % single-subject images', total_count;

  -- Migrate existing single-subject images to new structure
  -- Populate subjects JSONB array from existing breed_id/coat_id
  UPDATE public.image_catalog
  SET subjects = jsonb_build_array(
    jsonb_build_object(
      'subject_order', 1,
      'is_primary', true,
      'breed_id', breed_id::text,
      'coat_id', COALESCE(coat_id::text, null),
      'position', 'center',
      'size_prominence', 'primary',
      'pose_description', 'portrait pose',
      'identified_by_ai', false,
      'ai_confidence', null
    )
  ),
  is_multi_subject = false
  WHERE breed_id IS NOT NULL
    AND is_multi_subject = false
    AND subjects = '[]'::jsonb;

  GET DIAGNOSTICS migrated_count = ROW_COUNT;
  RAISE NOTICE 'Migrated % single-subject images to new subjects structure', migrated_count;

  -- Create junction table entries for existing images
  INSERT INTO public.image_catalog_subjects (
    image_id,
    subject_order,
    is_primary,
    breed_id,
    coat_id,
    outfit_id,
    position_in_frame,
    size_prominence,
    identified_by_ai,
    pose_description
  )
  SELECT
    ic.id as image_id,
    1 as subject_order,
    true as is_primary,
    ic.breed_id,
    ic.coat_id,
    ic.outfit_id,
    'center' as position_in_frame,
    'primary' as size_prominence,
    false as identified_by_ai,
    'portrait pose' as pose_description
  FROM public.image_catalog ic
  WHERE ic.breed_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM public.image_catalog_subjects ics
      WHERE ics.image_id = ic.id
    )
  ON CONFLICT (image_id, subject_order) DO NOTHING;

  GET DIAGNOSTICS migrated_count = ROW_COUNT;
  RAISE NOTICE 'Created % junction table entries for existing images', migrated_count;

  RAISE NOTICE 'Backward compatibility migration completed successfully';
END $$;

-- =============================================================================
-- 5. UPDATE EXISTING RLS POLICIES (if needed)
-- =============================================================================

-- Note: Existing RLS policies on image_catalog should work with new columns
-- The junction table inherits security through the CASCADE foreign key
-- If additional policies are needed, add them here

-- =============================================================================
-- 6. GRANT PERMISSIONS
-- =============================================================================

-- Grant read access to authenticated users
GRANT SELECT ON public.image_catalog_subjects TO authenticated;

-- Grant full access to service role
GRANT ALL ON public.image_catalog_subjects TO service_role;

-- =============================================================================
-- 7. VERIFICATION QUERIES
-- =============================================================================

-- Verify new columns exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'image_catalog'
      AND column_name = 'is_multi_subject'
  ) THEN
    RAISE EXCEPTION 'Column is_multi_subject was not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'image_catalog'
      AND column_name = 'subjects'
  ) THEN
    RAISE EXCEPTION 'Column subjects was not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'image_catalog'
      AND column_name = 'composition_analysis'
  ) THEN
    RAISE EXCEPTION 'Column composition_analysis was not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'image_catalog'
      AND column_name = 'variation_prompt_template'
  ) THEN
    RAISE EXCEPTION 'Column variation_prompt_template was not created';
  END IF;

  RAISE NOTICE 'All new image_catalog columns created successfully';
END $$;

-- Verify junction table exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename = 'image_catalog_subjects'
  ) THEN
    RAISE EXCEPTION 'Table image_catalog_subjects was not created';
  END IF;

  RAISE NOTICE 'Junction table image_catalog_subjects created successfully';
END $$;

-- Verify indexes created
SELECT
  schemaname,
  tablename,
  indexname
FROM pg_indexes
WHERE schemaname = 'public'
  AND (
    tablename = 'image_catalog'
    AND indexname LIKE 'idx_image_catalog_%_gin'
    OR tablename = 'image_catalog_subjects'
  )
ORDER BY tablename, indexname;

-- =============================================================================
-- 8. MIGRATION STATISTICS
-- =============================================================================

-- Show migration summary
SELECT
  'Total catalog images' as metric,
  COUNT(*) as value
FROM public.image_catalog
UNION ALL
SELECT
  'Single-subject images (migrated)',
  COUNT(*)
FROM public.image_catalog
WHERE is_multi_subject = false AND subjects != '[]'::jsonb
UNION ALL
SELECT
  'Multi-subject images',
  COUNT(*)
FROM public.image_catalog
WHERE is_multi_subject = true
UNION ALL
SELECT
  'Images with AI analysis',
  COUNT(*)
FROM public.image_catalog
WHERE ai_analyzed_at IS NOT NULL
UNION ALL
SELECT
  'Junction table entries',
  COUNT(*)
FROM public.image_catalog_subjects
UNION ALL
SELECT
  'Primary subjects',
  COUNT(*)
FROM public.image_catalog_subjects
WHERE is_primary = true;

-- =============================================================================
-- ROLLBACK INSTRUCTIONS
-- =============================================================================
-- To rollback this migration (WARNING: Will lose multi-subject data):
/*
BEGIN;

-- Drop junction table
DROP TABLE IF EXISTS public.image_catalog_subjects CASCADE;

-- Remove new columns
ALTER TABLE public.image_catalog
  DROP COLUMN IF EXISTS is_multi_subject,
  DROP COLUMN IF EXISTS subjects,
  DROP COLUMN IF EXISTS composition_analysis,
  DROP COLUMN IF EXISTS composition_metadata,
  DROP COLUMN IF EXISTS ai_analysis_model,
  DROP COLUMN IF EXISTS ai_analyzed_at,
  DROP COLUMN IF EXISTS marketing_description,
  DROP COLUMN IF EXISTS marketing_description_approved,
  DROP COLUMN IF EXISTS variation_prompt_template;

-- Drop indexes (will cascade with column drops, but explicit for clarity)
DROP INDEX IF EXISTS public.idx_image_catalog_is_multi_subject;
DROP INDEX IF EXISTS public.idx_image_catalog_ai_analyzed;
DROP INDEX IF EXISTS public.idx_image_catalog_marketing_approved;
DROP INDEX IF EXISTS public.idx_image_catalog_has_composition;
DROP INDEX IF EXISTS public.idx_image_catalog_subjects_gin;
DROP INDEX IF EXISTS public.idx_image_catalog_composition_metadata_gin;

COMMIT;
*/
