-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.breed_coats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  breed_id uuid NOT NULL,
  coat_id uuid NOT NULL,
  is_common boolean DEFAULT true,
  is_standard boolean DEFAULT true,
  popularity_rank integer,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT breed_coats_pkey PRIMARY KEY (id),
  CONSTRAINT breed_coats_coat_id_fkey FOREIGN KEY (coat_id) REFERENCES public.coats(id),
  CONSTRAINT breed_coats_breed_id_fkey FOREIGN KEY (breed_id) REFERENCES public.breeds(id)
);
CREATE TABLE public.breeds (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  physical_traits jsonb DEFAULT '{}'::jsonb,
  personality_traits ARRAY,
  alternative_names ARRAY,
  popularity_rank integer,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT breeds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.client_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_email text NOT NULL,
  referral_id uuid,
  partner_id uuid,
  order_value numeric NOT NULL,
  discount_applied numeric DEFAULT 0,
  is_initial_order boolean DEFAULT true,
  commission_rate numeric,
  commission_amount numeric,
  commission_paid boolean DEFAULT false,
  payment_id uuid,
  order_items jsonb,
  order_status text DEFAULT 'pending'::text CHECK (order_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'cancelled'::text, 'refunded'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  customer_id uuid,
  CONSTRAINT client_orders_pkey PRIMARY KEY (id),
  CONSTRAINT client_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT client_orders_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.commission_payments(id),
  CONSTRAINT client_orders_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT client_orders_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id)
);
CREATE TABLE public.coats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text,
  hex_color text,
  pattern_type text,
  rarity text DEFAULT 'common'::text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT coats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.commission_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  payment_period_start date NOT NULL,
  payment_period_end date NOT NULL,
  total_amount numeric NOT NULL,
  referral_count integer NOT NULL DEFAULT 0,
  initial_commission_amount numeric DEFAULT 0,
  lifetime_commission_amount numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'paid'::text, 'failed'::text, 'cancelled'::text])),
  payment_method text NOT NULL,
  payment_details jsonb,
  failure_reason text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commission_payments_pkey PRIMARY KEY (id),
  CONSTRAINT commission_payments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.countries (
  code text NOT NULL,
  name text NOT NULL,
  currency_code text NOT NULL,
  currency_symbol text NOT NULL,
  is_supported boolean DEFAULT true,
  shipping_zone text,
  tax_rate_percent numeric DEFAULT 0,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT countries_pkey PRIMARY KEY (code)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  first_name text,
  last_name text,
  phone text,
  user_id uuid,
  is_registered boolean DEFAULT false,
  pets jsonb DEFAULT '[]'::jsonb,
  marketing_consent boolean DEFAULT false,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  total_orders integer DEFAULT 0,
  total_spent numeric DEFAULT 0,
  first_order_date timestamp with time zone,
  last_order_date timestamp with time zone,
  referred_by_partner_id uuid,
  referral_code text,
  referral_date timestamp with time zone,
  notes text,
  tags ARRAY DEFAULT '{}'::text[],
  customer_status text DEFAULT 'active'::text CHECK (customer_status = ANY (ARRAY['active'::text, 'inactive'::text, 'blocked'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_referred_by_partner_id_fkey FOREIGN KEY (referred_by_partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.format_theme_combinations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  format_id uuid,
  theme_id uuid,
  compatibility_score integer DEFAULT 5,
  custom_adjustments text,
  is_recommended boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT format_theme_combinations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.formats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  aspect_ratio text NOT NULL,
  use_case text NOT NULL,
  prompt_adjustments text,
  midjourney_parameters text DEFAULT '--style raw --v 6'::text,
  technical_specs jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  size_code text,
  width_cm numeric,
  height_cm numeric,
  is_square boolean DEFAULT false,
  display_order integer DEFAULT 0,
  CONSTRAINT formats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.generated_prompts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  breed_id uuid,
  theme_id uuid,
  style_id uuid,
  format_id uuid,
  template_id uuid,
  final_prompt text NOT NULL,
  generation_parameters jsonb DEFAULT '{}'::jsonb,
  quality_rating integer,
  notes text,
  generated_image_urls ARRAY,
  is_approved boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT generated_prompts_pkey PRIMARY KEY (id),
  CONSTRAINT generated_prompts_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.prompt_templates(id),
  CONSTRAINT generated_prompts_style_id_fkey FOREIGN KEY (style_id) REFERENCES public.styles(id),
  CONSTRAINT generated_prompts_format_id_fkey FOREIGN KEY (format_id) REFERENCES public.formats(id),
  CONSTRAINT generated_prompts_breed_id_fkey FOREIGN KEY (breed_id) REFERENCES public.breeds(id),
  CONSTRAINT generated_prompts_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.themes(id)
);
CREATE TABLE public.image_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  filename text NOT NULL,
  original_filename text NOT NULL,
  file_size integer NOT NULL,
  mime_type text NOT NULL,
  storage_path text NOT NULL,
  public_url text NOT NULL,
  prompt_text text NOT NULL,
  description text,
  tags ARRAY DEFAULT '{}'::text[],
  breed_id uuid,
  theme_id uuid,
  style_id uuid,
  format_id uuid,
  coat_id uuid,
  ai_model text,
  generation_parameters jsonb DEFAULT '{}'::jsonb,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  is_featured boolean DEFAULT false,
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  share_count integer DEFAULT 0,
  last_shared_at timestamp with time zone,
  like_count integer DEFAULT 0,
  view_count integer DEFAULT 0,
  last_liked_at timestamp with time zone,
  last_viewed_at timestamp with time zone,
  CONSTRAINT image_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT image_catalog_breed_id_fkey FOREIGN KEY (breed_id) REFERENCES public.breeds(id),
  CONSTRAINT image_catalog_format_id_fkey FOREIGN KEY (format_id) REFERENCES public.formats(id),
  CONSTRAINT image_catalog_style_id_fkey FOREIGN KEY (style_id) REFERENCES public.styles(id),
  CONSTRAINT image_catalog_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.themes(id),
  CONSTRAINT image_catalog_coat_id_fkey FOREIGN KEY (coat_id) REFERENCES public.coats(id)
);
CREATE TABLE public.interaction_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  image_id uuid NOT NULL,
  total_likes integer DEFAULT 0,
  total_unlikes integer DEFAULT 0,
  net_likes integer DEFAULT 0,
  total_shares integer DEFAULT 0,
  total_views integer DEFAULT 0,
  unique_users integer DEFAULT 0,
  unique_likers integer DEFAULT 0,
  unique_sharers integer DEFAULT 0,
  unique_viewers integer DEFAULT 0,
  first_interaction_at timestamp with time zone,
  last_interaction_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT interaction_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT interaction_analytics_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.image_catalog(id)
);
CREATE TABLE public.media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  category text,
  material_type text,
  finish_type text,
  thickness_mm numeric,
  indoor_outdoor text CHECK (indoor_outdoor = ANY (ARRAY['indoor'::text, 'outdoor'::text, 'both'::text])),
  uv_resistant boolean DEFAULT false,
  water_resistant boolean DEFAULT false,
  care_instructions text,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  gelato_category text,
  base_cost_multiplier numeric DEFAULT 1.0,
  meta_title text,
  meta_description text,
  preview_image_url text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id text NOT NULL,
  image_id text NOT NULL,
  image_url text NOT NULL,
  image_title text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price integer NOT NULL,
  total_price integer NOT NULL,
  product_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'confirmed'::text,
  customer_email text NOT NULL,
  shipping_first_name text NOT NULL,
  shipping_last_name text NOT NULL,
  shipping_address text NOT NULL,
  shipping_city text NOT NULL,
  shipping_postcode text NOT NULL,
  shipping_country text NOT NULL DEFAULT 'United Kingdom'::text,
  subtotal_amount integer NOT NULL,
  shipping_amount integer NOT NULL DEFAULT 0,
  total_amount integer NOT NULL,
  currency text NOT NULL DEFAULT 'GBP'::text,
  estimated_delivery timestamp with time zone,
  tracking_number text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text,
  business_name text,
  business_type text CHECK (business_type = ANY (ARRAY['groomer'::text, 'breeder'::text, 'vet'::text, 'salon'::text, 'mobile'::text, 'independent'::text, 'chain'::text])),
  business_address jsonb,
  business_phone text,
  business_website text,
  bio text,
  avatar_url text,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  onboarding_completed boolean DEFAULT false,
  payment_method text CHECK (payment_method = ANY (ARRAY['paypal'::text, 'bank_transfer'::text])),
  payment_details jsonb,
  notification_preferences jsonb DEFAULT '{"sms_enabled": false, "email_referrals": true, "email_commissions": true}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approval_status text DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'suspended'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  last_login_at timestamp with time zone,
  commission_rate numeric DEFAULT 20.00,
  lifetime_commission_rate numeric DEFAULT 5.00,
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pet_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pet_id uuid NOT NULL,
  photo_url text NOT NULL,
  is_primary boolean DEFAULT false,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pet_photos_pkey PRIMARY KEY (id),
  CONSTRAINT pet_photos_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id)
);
CREATE TABLE public.pets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  customer_id uuid,
  name text NOT NULL,
  breed_id uuid,
  coat_id uuid,
  age integer,
  birthday date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'unknown'::text])),
  weight numeric,
  primary_photo_url text,
  photo_urls ARRAY DEFAULT '{}'::text[],
  personality_traits ARRAY,
  special_notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pets_pkey PRIMARY KEY (id),
  CONSTRAINT pets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT pets_breed_id_fkey FOREIGN KEY (breed_id) REFERENCES public.breeds(id),
  CONSTRAINT pets_coat_id_fkey FOREIGN KEY (coat_id) REFERENCES public.coats(id),
  CONSTRAINT pets_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.platform_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  image_id uuid NOT NULL,
  platform text NOT NULL,
  total_platform_shares integer DEFAULT 0,
  unique_platform_sharers integer DEFAULT 0,
  first_shared_at timestamp with time zone,
  last_shared_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT platform_analytics_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.image_catalog(id)
);
CREATE TABLE public.product_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  country_code text NOT NULL,
  product_cost integer NOT NULL,
  shipping_cost integer NOT NULL DEFAULT 0,
  sale_price integer NOT NULL,
  currency_code text NOT NULL,
  currency_symbol text NOT NULL,
  discount_price integer,
  is_on_sale boolean DEFAULT false,
  sale_start_date timestamp with time zone,
  sale_end_date timestamp with time zone,
  profit_amount integer,
  profit_margin_percent numeric,
  markup_percent numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT product_pricing_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_pricing_country_code_fkey FOREIGN KEY (country_code) REFERENCES public.countries(code)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  medium_id uuid NOT NULL,
  format_id uuid NOT NULL,
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  gelato_product_id text,
  gelato_variant_id text,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  stock_status text DEFAULT 'in_stock'::text CHECK (stock_status = ANY (ARRAY['in_stock'::text, 'low_stock'::text, 'out_of_stock'::text, 'discontinued'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  size_name text,
  size_code text,
  width_cm numeric,
  height_cm numeric,
  width_inches numeric,
  height_inches numeric,
  gelato_sku text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_medium_id_fkey FOREIGN KEY (medium_id) REFERENCES public.media(id),
  CONSTRAINT products_format_id_fkey FOREIGN KEY (format_id) REFERENCES public.formats(id)
);
CREATE TABLE public.prompt_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  template text NOT NULL,
  variables jsonb NOT NULL,
  ai_platform text NOT NULL DEFAULT 'midjourney'::text,
  version text DEFAULT 'v1'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT prompt_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referral_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['qr_scan'::text, 'email_open'::text, 'link_click'::text, 'page_view'::text, 'order_start'::text, 'order_complete'::text])),
  event_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT referral_analytics_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id)
);
CREATE TABLE public.referral_status_backup (
  id uuid,
  status text,
  created_at timestamp with time zone
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  referral_code text NOT NULL UNIQUE,
  client_name text NOT NULL,
  client_email text NOT NULL,
  client_phone text,
  client_notes text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['invited'::text, 'accessed'::text, 'accepted'::text, 'applied'::text, 'expired'::text])),
  qr_code_url text,
  qr_scans integer DEFAULT 0,
  email_opens integer DEFAULT 0,
  last_viewed_at timestamp with time zone,
  order_id uuid,
  order_value numeric,
  discount_amount numeric,
  commission_rate numeric DEFAULT 20.00,
  lifetime_commission_rate numeric DEFAULT 5.00,
  commission_amount numeric,
  commission_paid boolean DEFAULT false,
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  purchased_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pet_name text,
  pet_breed_id uuid,
  pet_coat_id uuid,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_pet_coat_id_fkey FOREIGN KEY (pet_coat_id) REFERENCES public.coats(id),
  CONSTRAINT referrals_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT referrals_pet_breed_id_fkey FOREIGN KEY (pet_breed_id) REFERENCES public.breeds(id)
);
CREATE TABLE public.share_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  image_id uuid NOT NULL,
  user_id uuid,
  user_email text,
  platform text NOT NULL,
  share_url text NOT NULL,
  user_agent text,
  ip_address inet,
  referrer text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT share_events_pkey PRIMARY KEY (id),
  CONSTRAINT share_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT share_events_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.image_catalog(id)
);
CREATE TABLE public.share_social_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  share_event_id uuid NOT NULL,
  social_account_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT share_social_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT share_social_accounts_social_account_id_fkey FOREIGN KEY (social_account_id) REFERENCES public.social_accounts(id),
  CONSTRAINT share_social_accounts_share_event_id_fkey FOREIGN KEY (share_event_id) REFERENCES public.share_events(id)
);
CREATE TABLE public.social_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform text NOT NULL,
  platform_user_id text,
  username text,
  display_name text,
  profile_url text,
  follower_count integer,
  verified boolean DEFAULT false,
  last_shared_at timestamp with time zone,
  first_shared_at timestamp with time zone DEFAULT now(),
  total_shares integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.styles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  prompt_suffix text NOT NULL,
  technical_parameters jsonb DEFAULT '{}'::jsonb,
  compatible_themes ARRAY,
  difficulty_level integer DEFAULT 1,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  midjourney_sref text,
  reference_image_url text,
  CONSTRAINT styles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.theme_style_combinations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  theme_id uuid,
  style_id uuid,
  compatibility_score integer DEFAULT 5,
  custom_prompt_adjustments text,
  example_tags ARRAY,
  is_recommended boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT theme_style_combinations_pkey PRIMARY KEY (id),
  CONSTRAINT theme_style_combinations_style_id_fkey FOREIGN KEY (style_id) REFERENCES public.styles(id),
  CONSTRAINT theme_style_combinations_theme_id_fkey FOREIGN KEY (theme_id) REFERENCES public.themes(id)
);
CREATE TABLE public.themes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  description text NOT NULL,
  base_prompt_template text NOT NULL,
  style_keywords ARRAY,
  seasonal_relevance jsonb DEFAULT '{}'::jsonb,
  difficulty_level integer DEFAULT 1,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT themes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text,
  image_id uuid NOT NULL,
  interaction_type text NOT NULL CHECK (interaction_type = ANY (ARRAY['like'::text, 'share'::text, 'unlike'::text, 'view'::text])),
  platform text,
  user_agent text,
  ip_address inet,
  referrer text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT user_interactions_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.image_catalog(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_type text NOT NULL CHECK (user_type = ANY (ARRAY['admin'::text, 'partner'::text, 'customer'::text])),
  permissions ARRAY DEFAULT '{}'::text[],
  partner_id uuid,
  customer_id uuid,
  first_name text,
  last_name text,
  email text,
  phone text,
  avatar_url text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT user_profiles_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);