/**
 * Builds db/migrations/2026-10-07-collections-seed.sql from lib/collections/definitions.ts
 * (occasions, sports leagues + 135 teams with their kit outfits, 16 Pawsonalities, 12 zodiac signs).
 * Run: npm run build:collections-seed. Ids are deterministic (uuid v5 of the path), so re-running
 * the SQL is safe: existing rows keep admin edits (names, seasons, order, pictures); team kit
 * prompts and colours are refreshed.
 */
import { createHash } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { allCollections } from '../lib/collections/definitions';

const uuid5 = (name: string) => {
  const h = createHash('sha1').update(`pawtraits-collections:${name}`).digest();
  h[6] = (h[6] & 0x0f) | 0x50; h[8] = (h[8] & 0x3f) | 0x80;
  const x = h.subarray(0, 16).toString('hex');
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20, 32)}`;
};
const q = (s: unknown) => (s === null || s === undefined ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`);
const arr = (a: string[] = []) => `ARRAY[${a.map(q).join(', ')}]::text[]`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const root = path.resolve(__dirname, '..');
const quiz = JSON.parse(readFileSync(path.join(root, 'db/seeds/pawsonality-content.json'), 'utf8'));
const dog = quiz.quizzes.find((x: any) => x.animalType === 'dog'), cat = quiz.quizzes.find((x: any) => x.animalType === 'cat');
const types = dog.resultTypes.map((t: any) => ({ code: t.code, dogName: t.name, catName: cat.resultTypes.find((c: any) => c.code === t.code)?.name ?? t.name }));
const defs = allCollections(types);

let sql = `-- =============================================================================
-- Seed: collections (occasions, sports leagues + teams with kit outfits, 16 Pawsonalities,
-- 12 zodiac signs). Generated by scripts/build-collections-seed.ts — edit in Admin → Collections
-- after this, not here. Safe to re-run. Run after 2026-10-07-collections.sql.
-- ${defs.length} collections, ${defs.filter(d => d.outfit).length} team outfits.
-- =============================================================================

BEGIN;

`;
// Team outfits first (collections reference them)
for (const d of defs.filter(x => x.outfit)) {
  const o = d.outfit!;
  sql += `INSERT INTO public.outfits (id, name, slug, description, clothing_description, color_scheme, style_keywords, animal_compatibility, is_active, sort_order)
VALUES (${q(uuid5('outfit:' + o.slug))}, ${q(o.name)}, ${q(o.slug)}, ${q(`Team kit for ${d.name} (Collections › Sports)`)}, ${q(o.clothing)}, ${arr(o.colours)}, ${arr(o.keywords)}, ARRAY['dog','cat']::text[], true, 500)
ON CONFLICT (slug) DO UPDATE SET clothing_description = EXCLUDED.clothing_description, color_scheme = EXCLUDED.color_scheme, updated_at = now();
`;
}
sql += '\n';
const order: Record<string, number> = {};
for (const d of defs) {
  const parentPath = d.path.includes('/') ? d.path.slice(0, d.path.lastIndexOf('/')) : null;
  const depth = d.path.split('/').length - 1;
  order[parentPath ?? ''] = (order[parentPath ?? ''] ?? 0) + 1;
  const outfitId = d.outfit ? `(SELECT id FROM public.outfits WHERE slug = ${q(d.outfit.slug)})` : 'NULL';
  sql += `INSERT INTO public.collections (id, kind, parent_id, slug, path, depth, name, short_name, description, season_windows, outfit_id, metadata, search_terms, sort_order)
VALUES (${q(uuid5(d.path))}, ${q(d.kind)}, ${parentPath ? `(SELECT id FROM public.collections WHERE path = ${q(parentPath)})` : 'NULL'}, ${q(d.slug)}, ${q(d.path)}, ${depth}, ${q(d.name)}, ${q(d.shortName ?? null)}, ${q(d.description ?? null)}, ${json(d.seasons ?? [])}, ${outfitId}, ${json(d.metadata ?? {})}, ${arr(d.searchTerms ?? [])}, ${order[parentPath ?? ''] * 10})
ON CONFLICT (path) DO UPDATE SET outfit_id = EXCLUDED.outfit_id, metadata = public.collections.metadata || EXCLUDED.metadata, search_terms = EXCLUDED.search_terms, updated_at = now();
`;
}
sql += '\nCOMMIT;\n';
writeFileSync(path.join(root, 'db/migrations/2026-10-07-collections-seed.sql'), sql);
console.log(`Wrote ${defs.length} collections (${defs.filter(d => d.outfit).length} teams)`);
