/**
 * Builds db/migrations/2026-10-01-pawsonality-seed.sql from db/seeds/pawsonality-content.json.
 * Run: npx tsx scripts/build-quiz-seed.ts
 * Ids are deterministic (uuid v5 from the content key), so re-running the SQL is safe and
 * the published version 1 snapshot points at the same question rows.
 */
import { createHash } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

const NS = 'pawtraits-quiz';
function uuid5(name: string): string {
  const h = createHash('sha1').update(`${NS}:${name}`).digest();
  h[6] = (h[6] & 0x0f) | 0x50;
  h[8] = (h[8] & 0x3f) | 0x80;
  const x = h.subarray(0, 16).toString('hex');
  return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20, 32)}`;
}
const q = (s: unknown) => (s === null || s === undefined ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`);
const arr = (a: string[] = []) => `ARRAY[${a.map(q).join(', ')}]::text[]`;

const root = path.resolve(__dirname, '..');
const data = JSON.parse(readFileSync(path.join(root, 'db/seeds/pawsonality-content.json'), 'utf8'));

let sql = `-- =============================================================================
-- Seed: 16 Pawsonalities content (dogs and cats), published as version 1.
-- Generated by scripts/build-quiz-seed.ts from db/seeds/pawsonality-content.json — edit
-- content in Admin → Quizzes after this, not here. Safe to re-run (inserts are skipped
-- when the rows exist). Run after 2026-10-01-quiz-engine.sql.
-- =============================================================================

BEGIN;
`;

for (const quiz of data.quizzes) {
  const quizId = uuid5(`quiz:${quiz.slug}:${quiz.animalType}`);
  sql += `\n-- ${quiz.title}\nINSERT INTO public.quizzes (id, slug, animal_type, title, status, current_version)\nVALUES (${q(quizId)}, ${q(quiz.slug)}, ${q(quiz.animalType)}, ${q(quiz.title)}, 'live', 1)\nON CONFLICT (slug, animal_type) DO NOTHING;\n\n`;

  const snapQuestions: any[] = [];
  quiz.questions.forEach((x: any, i: number) => {
    const id = uuid5(`question:${x.key}`);
    sql += `INSERT INTO public.quiz_questions (id, quiz_id, dimension, right_pole, statement, share_quote, visual_brief, sort_order, is_active)\nVALUES (${q(id)}, ${q(quizId)}, ${q(x.dimension)}, ${q(x.rightPole)}, ${q(x.statement)}, ${q(x.shareQuote)}, ${q(x.visualBrief)}, ${i + 1}, ${x.isActive ? 'true' : 'false'})\nON CONFLICT (id) DO NOTHING;\n`;
    if (x.isActive) snapQuestions.push({ id, dimension: x.dimension, rightPole: x.rightPole, statement: x.statement, shareQuote: x.shareQuote, visualBrief: x.visualBrief, imagePublicId: null });
  });
  sql += '\n';

  const snapTypes: any[] = [];
  for (const t of quiz.resultTypes) {
    const id = uuid5(`type:${quiz.animalType}:${t.code}`);
    sql += `INSERT INTO public.quiz_result_types (id, quiz_id, code, name, tagline, traits, signature_move, owner_reality, share_quote)\nVALUES (${q(id)}, ${q(quizId)}, ${q(t.code)}, ${q(t.name)}, ${q(t.tagline)}, ${arr(t.traits)}, ${q(t.signatureMove)}, ${q(t.ownerReality)}, ${q(t.shareQuote)})\nON CONFLICT (quiz_id, code) DO NOTHING;\n`;
    snapTypes.push({ code: t.code, name: t.name, tagline: t.tagline, traits: t.traits, signatureMove: t.signatureMove, ownerReality: t.ownerReality, shareQuote: t.shareQuote, designImageId: null });
  }

  const content = JSON.stringify({ questions: snapQuestions, resultTypes: snapTypes });
  sql += `\nINSERT INTO public.quiz_versions (quiz_id, version, content)\nVALUES (${q(quizId)}, 1, ${q(content)}::jsonb)\nON CONFLICT (quiz_id, version) DO NOTHING;\n`;
}

sql += '\nCOMMIT;\n';
const out = path.join(root, 'db/migrations/2026-10-01-pawsonality-seed.sql');
writeFileSync(out, sql);
console.log(`Wrote ${out}`);
