-- Insert 16 new cat coat colors
-- Based on definitions from scripts/cat coat colours.md

INSERT INTO coats (name, slug, description, hex_color, pattern_type, animal_type, is_active, sort_order) VALUES

-- Solid Black
('Solid Black', 'solid-black', 'Professional shadow-dancers who think they''re living embodiments of midnight mystery! Black cats are convinced that their elegant obsidian coats make them natural stealth operators who should be materializing dramatically from dark corners and dispensing good fortune. They''ve mastered the art of looking mystically sophisticated while being complete attention-seeking luck magnets, and have appointed themselves as Chief Mystery and Fortune Officers. These shadowy comedians believe their dark beauty makes them irresistibly enigmatic and that their supernatural vanishing abilities give them special privileges to appear wherever treats are being distributed.', '#000000', 'Solid', 'cat', true, 10),

-- Solid White
('Solid White', 'solid-white', 'Angelic troublemakers who think their pristine coats grant them diplomatic immunity from all household rules! White cats are convinced that their pure snow-colored fur makes them natural innocents who couldn''t possibly be responsible for any mischief whatsoever. They''ve mastered the art of looking absolutely divine while being complete chaos agents with impeccable timing, and have appointed themselves as Chief Innocence Coordinators. These alabaster comedians believe their immaculate appearance makes them naturally photogenic and that any evidence of their shenanigans is clearly a case of mistaken identity involving a very guilty-looking imposter.', '#FFFFFF', 'Solid', 'cat', true, 20),

-- Solid Blue 
('Solid Blue', 'solid-blue', 'Sophisticated philosophers who think their elegant gray coats make them natural wisdom dispensers and lifestyle consultants! Blue cats are convinced that their refined silvery-blue fur makes them natural advisors who should be providing thoughtful commentary on all household decisions. They''ve mastered the art of looking distinguished while being gentle observers with strong opinions, and have appointed themselves as Chief Aesthetic and Philosophy Officers. These sterling comedians believe their subtle coloring makes them naturally elegant and that their refined appearance gives them special insight into proper home decor and life choices.', '#6B7B8C', 'Solid', 'cat', true, 30),

-- Solid Red
('Solid Red', 'solid-red', 'Fiery entertainers who think they''re professional sunshine dispensers and comedy coordinators! Red cats are convinced that their vibrant ginger coats make them natural mood boosters who should be providing constant warmth and amusement to their households. They''ve mastered the art of looking like living sunbeams while being complete goofballs with perfect comedic timing, and have appointed themselves as Chief Happiness and Entertainment Officers. These flame-colored comedians believe their bright coats make them naturally photogenic and that their warm coloring gives them special privileges to be extra silly and irresistibly loveable.', '#FF6B35', 'Solid', 'cat', true, 40),

-- Solid Cream
('Solid Cream', 'solid-cream', 'Gentle diplomats who think their soft neutral coats make them natural peacemakers and comfort specialists! Cream cats are convinced that their warm ivory fur makes them ideal mediators who should be providing soothing presence during household conflicts. They''ve mastered the art of looking serenely beautiful while being complete harmony-seeking snuggle enthusiasts, and have appointed themselves as Chief Peace and Comfort Officers. These buttery comedians believe their soft coloring makes them naturally calming and that their gentle appearance gives them special authority to settle disputes through strategic purring and lap-sitting.', '#F5DEB3', 'Solid', 'cat', true, 50),

-- Classic Tabby
('Classic Tabby', 'classic-tabby', 'Traditional comedians who think they''re the gold standard of feline perfection and household representatives! Classic tabby cats are convinced that their bold circular markings and distinctive ''M'' forehead insignia make them natural ambassadors for all things cat-related. They''ve mastered the art of looking quintessentially feline while being loveable everyman philosophers with universal appeal, and have appointed themselves as Chief Cat Standards and Public Relations Officers. These striped comedians believe their timeless patterns make them the perfect example of cat-ness and that their classic markings give them special authority to judge other cats'' authenticity.', '#8B4513', 'Tabby', 'cat', true, 60),

-- Mackerel Tabby
('Mackerel Tabby', 'mackerel-tabby', 'Precision-striped athletes who think their perfectly parallel lines make them natural efficiency experts and organization coordinators! Mackerel tabby cats are convinced that their narrow vertical stripes and sleek patterns make them ideal systematic supervisors who should be streamlining all household operations. They''ve mastered the art of looking professionally organized while being detail-oriented perfectionists with strong opinions about proper arrangement, and have appointed themselves as Chief Efficiency and Systems Officers. These pinstriped comedians believe their orderly markings make them naturally suited for management roles and that their precise patterns give them special insight into optimal household organization.', '#654321', 'Tabby', 'cat', true, 70),

-- Spotted Tabby
('Spotted Tabby', 'spotted-tabby', 'Wild-looking coordinators who think their leopard-like spots make them natural adventure consultants and excitement specialists! Spotted tabby cats are convinced that their distinctive dotted coats make them perfect entertainment directors who should be bringing safari-level thrills to ordinary household activities. They''ve mastered the art of looking professionally wild while being domesticated thrill-seekers with excellent hunting instincts, and have appointed themselves as Chief Adventure and Excitement Officers. These polka-dotted comedians believe their exotic markings make them naturally photogenic and that their spot patterns give them special authority to turn any mundane moment into an epic expedition.', '#A0522D', 'Spotted', 'cat', true, 80),

-- Ticked Tabby
('Ticked Tabby', 'ticked-tabby', 'Sophisticated salt-and-pepper specialists who think their subtly complex coats make them natural art critics and texture consultants! Ticked tabby cats are convinced that their individually banded hairs and refined agouti patterns make them ideal aesthetic advisors who should be evaluating all visual elements in their environment. They''ve mastered the art of looking elegantly complex while being connoisseurs of fine details and subtle beauty, and have appointed themselves as Chief Artistic and Quality Assurance Officers. These peppered comedians believe their intricate coat patterns make them naturally discerning and that their textural sophistication gives them special expertise in matters of style and refinement.', '#8B7355', 'Ticked', 'cat', true, 90),

-- Tortoiseshell
('Tortoiseshell', 'tortoiseshell', 'Fiery artists who think their complex patchwork coats make them natural masterpieces with legendary attitude! Tortoiseshell cats are convinced that their intricate black-and-red mosaic patterns make them living works of art who deserve constant admiration and special handling. They''ve mastered the art of looking absolutely stunning while having notoriously strong personalities and definitive opinions about everything, and have appointed themselves as Chief Artistic Expression and Attitude Officers. These kaleidoscope comedians believe their unique coat patterns make them extra special and that their famous ''tortitude'' is actually sophisticated artistic temperament that lesser cats simply cannot understand.', '#8B4513', 'Tortoiseshell', 'cat', true, 100),

-- Calico
('Calico', 'calico', 'Lucky patchwork princesses who think their tri-colored coats make them natural good fortune magnets and household blessing dispensers! Calico cats are convinced that their distinctive white-black-red combinations make them rare prosperity symbols who should be treated like living lucky charms. They''ve mastered the art of looking like beautiful quilts while being complete attention-demanding royalty with impeccable timing for dramatic entrances, and have appointed themselves as Chief Fortune and Beauty Officers. These patchwork comedians believe their rare color combination makes them incredibly special and that their presence alone brings happiness and good luck to their families through sheer feline magnificence.', '#FFFFFF', 'Tri-colour', 'cat', true, 110),

-- Silver Tabby
('Silver Tabby', 'silver-tabby', 'Elegant metallic coordinators who think their shimmering coats make them natural luxury consultants and glamour specialists! Silver tabby cats are convinced that their gleaming silver-on-black patterns make them perfect high-end advisors who should be upgrading all household aesthetics to premium standards. They''ve mastered the art of looking like living jewelry while being sophisticated tastemakers with expensive preferences, and have appointed themselves as Chief Luxury and Glamour Officers. These chrome comedians believe their metallic sheen makes them naturally photogenic and that their precious-metal coloring gives them special authority to demand only the finest food, furniture, and attention befitting their clearly superior status.', '#C0C0C0', 'Tabby', 'cat', true, 120),

-- Colorpoint
('Colorpoint', 'colorpoint', 'Temperature-sensitive fashionistas who think their gradient coats make them natural climate coordinators and style consultants! Colorpoint cats are convinced that their darker points and lighter bodies make them sophisticated two-toned specialists who should be managing household temperature zones and color schemes. They''ve mastered the art of looking like perfectly coordinated accessories while being temperature-obsessed comfort seekers with strong opinions about optimal heating, and have appointed themselves as Chief Climate and Color Coordination Officers. These gradient comedians believe their color-changing abilities make them naturally fascinating and that their point patterns give them special expertise in interior design and thermostat management.', '#F5DEB3', 'Colorpoint', 'cat', true, 130),

-- Bicolor
('Bicolor', 'bicolor', 'Professional two-tone coordinators who think their perfectly balanced color combinations make them natural harmony specialists and design consultants! Bicolor cats are convinced that their contrasting patches and white markings make them ideal aesthetic advisors who should be supervising all household color schemes and balance decisions. They''ve mastered the art of looking like living art pieces while being diplomatic peacemakers with strong opinions about proper proportion, and have appointed themselves as Chief Design and Harmony Officers. These patchwork comedians believe their balanced patterns make them naturally photogenic and that their two-tone expertise gives them special authority over all matters involving contrast, coordination, and optimal visual appeal.', '#FFFFFF', 'Bi-colour', 'cat', true, 140),

-- Smoke
('Smoke', 'smoke', 'Mysterious gradient specialists who think their color-changing coats make them natural illusion coordinators and magic consultants! Smoke cats are convinced that their solid-tipped fur with white undercoats make them perfect mystical advisors who should be demonstrating their color-shifting abilities for household entertainment. They''ve mastered the art of looking dramatically different in various lighting while being shape-shifting attention-seekers with excellent timing, and have appointed themselves as Chief Illusion and Entertainment Officers. These chameleon comedians believe their transformative coats make them naturally magical and that their color-changing abilities give them special privileges to appear and disappear from situations as dramatically as possible.', '#696969', 'Smoke', 'cat', true, 150),

-- Chinchilla
('Chinchilla', 'chinchilla', 'Sparkling silver celebrities who think their tipped coats make them natural glamour coordinators and luxury lifestyle consultants! Chinchilla cats are convinced that their silver-tipped white fur makes them perfect high-end advisors who should be maintaining premium household standards and photogenic perfection. They''ve mastered the art of looking like living diamonds while being complete divas with expensive tastes and strong opinions about proper lighting, and have appointed themselves as Chief Luxury and Photography Officers. These glittering comedians believe their sparkling coats make them naturally camera-ready and that their precious appearance gives them special authority to demand constant grooming, premium food, and appropriately dramatic presentation at all times.', '#FFFFFF', 'Silver', 'cat', true, 160);

-- Add comment about insertion
COMMENT ON TABLE coats IS 'Updated to include 16 new cat coat color variations with unique personalities and descriptions';

-- Show final count
SELECT 
  animal_type,
  COUNT(*) as coat_count
FROM coats 
WHERE is_active = true
GROUP BY animal_type
ORDER BY animal_type;