#!/bin/bash

# Phase 1 Database Migrations Runner
# Run with: ./scripts/run-phase1-migrations.sh

echo "🚀 Phase 1 Database Migrations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Migration files ready:"
echo "   1. phase1-01-extend-products-table.sql"
echo "   2. phase1-02-extend-orders-table.sql"
echo "   3. phase1-03-extend-order-items-table.sql"
echo "   4. phase1-04-create-order-fulfillment-tracking-table.sql"
echo "   5. phase1-05-backfill-existing-data.sql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 To run these migrations, you have two options:"
echo ""
echo "Option 1: Supabase SQL Editor (Recommended)"
echo "  1. Go to: https://supabase.com/dashboard/project/YOUR_PROJECT/sql/new"
echo "  2. Copy and paste each SQL file content in order (1-5)"
echo "  3. Click 'Run' for each migration"
echo ""
echo "Option 2: Direct psql Connection"
echo "  1. Get your database connection string from Supabase dashboard"
echo "  2. Run each migration:"
echo "     psql 'postgresql://...' < scripts/phase1-01-extend-products-table.sql"
echo "     psql 'postgresql://...' < scripts/phase1-02-extend-orders-table.sql"
echo "     psql 'postgresql://...' < scripts/phase1-03-extend-order-items-table.sql"
echo "     psql 'postgresql://...' < scripts/phase1-04-create-order-fulfillment-tracking-table.sql"
echo "     psql 'postgresql://...' < scripts/phase1-05-backfill-existing-data.sql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 After migrations complete:"
echo "  - Run: npx tsx scripts/update-schema-file.ts"
echo "  - Verify schema changes applied correctly"
echo ""
